# Generated by Django 5.1.1 on 2025-07-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=255, unique=True)),
                ('page_name', models.CharField(max_length=255)),
                ('user_access_token', models.TextField()),
                ('page_access_token', models.TextField()),
                ('instagram_business_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
