# Generated by Django 5.1.1 on 2025-07-04 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_user_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('conversation_id', models.CharField(max_length=255)),
                ('last_message_text', models.TextField(blank=True, null=True)),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facebookpage')),
            ],
        ),
    ]
