# Generated by Django 5.1.1 on 2025-07-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instagramsender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstagramSender',
            new_name='InstagramSenderDetails',
        ),
    ]
