# Generated by Django 5.1.1 on 2025-07-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_instagramsender_instagramsenderdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramSenderMessageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('conversation_id', models.CharField(max_length=100)),
                ('sender_id', models.CharField(max_length=100)),
                ('sender_username', models.CharField(blank=True, max_length=150, null=True)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facebookpage')),
            ],
        ),
    ]
