# Generated by Django 5.1.1 on 2025-07-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_facebookpage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammessage',
            name='conversation_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instagrammessage',
            name='message_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='instagrammessage',
            name='sender_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instagrammessage',
            name='sender_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instagramsenderdetails',
            name='ig_user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
